### ISSUE TITLE
1.1.0 is broken

### ISSUE THREAD

**Issue by hugh-stevenson-tdl** [KELiON/cerebro-mac-apps#9]
1.1.0 is broken and can't find applications. I've done a fresh install and shows the same error message.

error message is 
`ReferenceError: string is not defined
    at VM2819 index.js:237:628
    at VM2819 index.js:1:904
    at Object.<anonymous> (VM2819 index.js:505:3125)
    at Object.<anonymous> (VM2819 index.js:628:3)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)`

**Comment by ChFlick** [comment]
Thanks for raising the issue, I'll fix that asap

**Comment by ChFlick** [comment]
Should be resolved now with v1.1.0, I think something just messed up the npm publishing.
Just comment if you still get errors :)
